version: '3.8'
  
services:
  postgres:
    image: michelangelodorado/warehouse-database-api:latest  # Use your Docker Hub username and image name
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: warehouse_db
    volumes:
      - ./database-svc/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    restart: always

  inventory-svc:
    image: michelangelodorado/warehouse-inventory-api:latest  # Replace with your Docker Hub username and image name
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    environment:
      DB_HOST: postgres
      DB_USER: admin
      DB_PASSWORD: password
      DB_NAME: warehouse_db
    restart: always

  pricing-svc:
    image: michelangelodorado/warehouse-pricing-api:latest  # Replace with your Docker Hub username and image name
    ports:
      - "3001:3001"
    depends_on:
      - postgres
    environment:
      DB_HOST: postgres
      DB_USER: admin
      DB_PASSWORD: password
      DB_NAME: warehouse_db
    restart: always
